Update to version 4
twitterdev/twitter-ruby-ads-sdk pull request #181
Opened 2019-01-02 07:52 UTC by abhishekgupta5

Changes in favour of migrating from version 3 to 4.
Referred from: https://developer.twitter.com/en/docs/ads/general/overview/versions

2019-01-02 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twitterdev/twitter-ruby-ads-sdk?pullRequest=181) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/twitterdev/twitter-ruby-ads-sdk?pullRequest=181) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: tushdante<br/>:x: anmolarora<br/>:x: abhishekgupta5<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twitterdev/twitter-ruby-ads-sdk?pullRequest=181) it.</sub>

2019-01-02 08:02 UTC, abhishekgupta5 commented
@jbabichjapan @tushdante Are you guys planning to update the gem for version 4 ? I see a few changes but version is still 3

2019-01-03 22:08 UTC, tushdante requested changes

2019-01-03 22:08 UTC, tushdante commented on lib/twitter-ads/account.rb
> +    # @return A Cursor or object instance.
This endpoint has been deprecated in v4 (i.e., the `:account_id/videos` endpoint). Feel free to remove this code block entirely.

2019-01-03 22:08 UTC, tushdante commented on lib/twitter-ads/client.rb
> +  API_VERSION = '4'.freeze
Lets keep this `3` for now, once all the other changes have been merged in, we'll make a separate version bump update.

2019-01-03 22:08 UTC, tushdante commented
Thanks for the updates @abhishekgupta5 ! Appreciate all the help! Requested a few changes but otherwise LGTM! We should be able to merge this PR #180 and then make the change to v4.

2019-02-18 08:36 UTC, closed without merging